include/znc/FileUtils.h
* Fixes warnings under musl-libc.
* <fcntl.h> should be universal in the Unix world, it's more likely a system doesn't have <sys/fcntl.h> than if it doesn't have <fcntl.h> (and has <sys/fcntl.h>.)
=> Change namespace for <fcntl.h>

modules/q.cpp
This patch ignores the value of JoinAfterCloaked unless UseCloakedHost
is set. Without this patch, it's possible to enable JoinAfterCloaked,
but not have UseCloakedHost enabled, which means that no channel will
ever be joined automatically by ZNC.
Fixes: #602
=> Q: Ignore JoinAfterCloaked unless UseCloakedHost is set

modules/savebuff.cpp, src/Query.cpp
The old internal storage format was:
::__:SAVEBUFF:__::<buffer lines>
The new storage format for channels:
::__:CHANBUFF:__::<buffer name>
<buffer lines>
The new storage format for queries:
::__:QUERYBUFF:__::<buffer name>
<buffer lines>
See #802 for details why the storage format had to be changed. Reading
the old storage format is still supported so old saved buffers load as
appropriate.
=> savebuff: save & load query buffers - fixes #802

include/znc/Threads.h, src/Threads.cpp
All values are protected by m_mutex. So we don't need the polling to
wait m_num_threads==0 with wakeups, instead simply use CConditionVariable.
=> Don't polling to wait the exit of threads in CThreadPool destructor

src/Client.cpp
In versions prior to 1.0, ZNC did not allow multiple networks per user. The string telling users to connect has never been changed after ZNC 1.0, and this fixes just that.
=> Tell user to use PASS <username>/<network> instead of just the username.

src/Client.cpp
Previously, it replied to CTCP VERSION, but only if no client is connected.
See https://github.com/znc/znc/issues/820#issuecomment-70506203
=> Add ZNC to CTCP VERSION reply even if client is connected.

src/Chan.cpp
A regression caused by aed1d61.
=> Fix #840 - channel hopping/cycling

modules/adminlog.cpp, modules/bouncedcc.cpp, modules/controlpanel.cpp, modules/dcc.cpp, modules/imapauth.cpp, modules/modules_online.cpp, modules/partyline.cpp, modules/schat.cpp, src/ClientCommand.cpp, src/HTTPSock.cpp, src/IRCSock.cpp, src/Modules.cpp, src/Template.cpp, src/Utils.cpp, src/ZNCString.cpp
Replace the use of deprecated CString::Equals(str,bool,int) by
CString::StartsWith(str,cs) which is more pleasant to read.
=> Use CString::StartsWith()

m4/ax_cxx_compile_stdcxx_11.m4
This fixes the following error (copied from config.log):
conftest.cpp:49:14: error: no previous declaration for 'void
test_template_alias_sfinae::test()' [-Werror=missing-declarations]
Signed-off-by: Uli Schlachter <psychon@znc.in>
=> configure: Fix C++11 test with -Werror=missing-declarations

modules/data/webadmin/tmpl/add_edit_user.tmpl, modules/data/webadmin/tmpl/settings.tmpl
Don't claim all networks/users have loaded a module when there are none
=> Fix #872: webadmin checkboxes

include/znc/ZNCString.h, src/ZNCString.cpp, test/StringTest.cpp
It's getting a common pattern to call AsLower() or MakeLower() on
the arguments passed to WildCmp(), we might as well add this for
convenience. It's tempting to make it case-insensitive by default,
since pretty much any IRC related comparison should be, but that
could potentially break some existing code.
=> CString::WildCmp(): add an optional case-sensitivity argument

include/znc/Chan.h, include/znc/Client.h, include/znc/IRCNetwork.h, include/znc/IRCSock.h, include/znc/Listener.h, include/znc/Modules.h, include/znc/Nick.h, include/znc/Socket.h, include/znc/Template.h, include/znc/User.h, include/znc/WebModules.h, include/znc/znc.h
include/znc/Foo.h: warning: ‘class CFoo’ has pointer data members [-Weffc++]
include/znc/Foo.h: warning:   but does not override ‘CFoo(const CFoo&)’ [-Weffc++]
include/znc/Foo.h: warning:   or ‘operator=(const CFoo&)’ [-Weffc++]
=> Fix copy ctor/assignment oper warnings of -Weffc++ (#270)

src/Socket.cpp
Building core object Socket...
src/Socket.cpp:30:16: warning: unused function 'ZNC_DefaultCipher' [-Wunused-function]
static CString ZNC_DefaultCipher() {
^
1 warning generated.
=> Fix compilation warning when HAVE_LIBSSL is not defined

webskins/_default_/pub/_default_.css
https://github.com/teward/znc/commit/7ad60cf6345ee818b55fd6278a62f1c1c203a8b3 details a change that makes the Fingerprints section look like this: 
The initial problem was that the info blurb was being smushed up next to the inputbox, making it look ugly (see #828)
After some fiddling, with different CSS, `clear`, `display: block`, and other settings, I was only able to make this work when expanding the width of the info div to accommodate the system, as is.  (This is only a bandaid, really, the actual CSS needs to be more defined for the "full subsection" blocks of code, as you have not yet defined in the default configuration file that class's div boundaries and such, and it causes breakages like #828)
=> Band-aid Fix CSS for _default_ for Fingerprints section (Fix #828)

modules/controlpanel.cpp, src/ClientCommand.cpp
Value stored to 'pUser' (during its initialization) is never read
=> Fix dead assign/init found by clang static analyzer

include/znc/HTTPSock.h, modules/bouncedcc.cpp, modules/ctcpflood.cpp, modules/keepnick.cpp
I forgot to run clang-modernize for modules/ and GCC 5 -Wsuggest-override spotted CHTTPSock::GetSockObj().
=> Add missing override keywords (#816)

.travis.yml, configure.ac
improves building on Mac OS X:
* icu4c is auto-detected if installed via Homebrew
* openssl is auto-detected if installed via Homebrew
* python3 is auto-detected if installed via Homebrew
The default is now to use openssl from Homebrew if available, as fallback it uses the system openssl.
If the environment variable `USE_SYSTEM_OPENSSL` is `"true"` then the system openssl is always used, no matter if a Homebrew version is installed.
Travis now tests using the Homebrew OpenSSL and the system OpenSSL on OS X.
=> add homebrew locations for openssl, icu4c, python3

modules/controlpanel.cpp
IMHO these placeholder names are the most obvious choice and easiest
to remember. For old-timers and to retain compatibility, $me is still
supported. For the advanced users there's also $net for convenience.
=> controlpanel: $user and $network (#847)

modules/chansaver.cpp
CModules::LoadModule() sets the module type _after_ construction.
The constructor cannot therefore do actions based on the module
type. Move loading to OnLoad().
=> Fix chansaver loading

include/znc/IRCNetwork.h, src/ClientCommand.cpp, src/IRCNetwork.cpp
Originally removed when query buffers were introduced in 14a534c.
The ideal name would be plural ClearQueryBuffers() now that there
are multiple query buffers, but use the old name for compatibility
reasons (see https://github.com/kylef/znc-contrib/pull/18).
=> Restore CIRCNetwork::ClearQueryBuffer() for convenience

modules/nickserv.cpp
Ref: https://github.com/znc/znc/issues/786#issuecomment-68104883
The NickServ command is usually server-side alias that ensures that
NickServ is U-lined server and not random user who has /nicked to
NickServ on misconfigured server that allows that.
NS would probably also work, but NICKSERV is more common.
Ref: https://github.com/ProgVal/Limnoria/pull/724#issuecomment-45381342
=> nickserv: use NICKSERV instead of PRIVMSG

modules/stickychan.cpp, src/Chan.cpp
* save registry on every stick/unstick action
* Currently the registry is only saved in the destructor - which might not get called if ZNC is crashes or gets terminated due to other reasons. 
* This PR changes the behaviour so that after every stick or unstick action the registry is saved. Therefore state changes are immediately reflected in the `.registry` file.
* auto-save if channel key changes
* Currently stickychan runs into troubles if a channel key changes and the user does not apply the same change again to stickychan (with the new key). 
* This PR monitors channel mode changes and updates or deletes the key if needed.
Overall I think this makes stickychan much more reliable and useful.
=> improve stickychan

modules/controlpanel.cpp
The User Deleted output for a success does not match the rest of the output formats for other commands and needs to match the same 'standard' for outputs.
=> Update 'User Deleted' message to match format

NOTICE
While I may not have made large contributions, I have provided changes in the past to provide standardization in message output format (such as for AddNetwork, DelNetwork, AddUser, DelUser, etc.) to both increase verbosity but to also provide information to the end user in a readable form (https://github.com/znc/znc/pull/353, https://github.com/znc/znc/pull/295).  Most recently, my last revision was extremely minor but enforces standardization of commands to those forms (https://github.com/znc/znc/pull/933).  I also (band-aid) fixed a display issue on webadmin for the SSLTrustedFingerprints caption (https://github.com/znc/znc/pull/859).
To that end, and the fact that the standardization and verbosity I set up is still in use today in a good portion of modules, I'd like my name added to …
=> Add Thomas Ward to contributors/helpers list

.gitignore, ChangeLog.md, include/znc/znc.h, src/ClientCommand.cpp, src/znc.cpp
This PR tries to reduce dangerous side effects of config parsing and `/znc rehash` invocation.
* remove very old ZNC settings and config parsing workarounds 
* everything *before* `v0.206` - meaning configs older than 3.5 years are invalid with the next release
* this affects: 
* ispoof: renamed to identfile in 0.200 (51ac51a25)
* config files without version string (introduced in 0.203)
* `/znc rehash` now only reloads the global config parts
* includes all global modules, listeners, and other global settings
* excludes reloading of users and all of their options
* this should make it *less dangerous*
* `OnAddUser` hook is now only called if actually a new user is added
* does not get called during ZNC startup any more (which used the same method)
During the refactor I tried splitting …
=> Refactor config parse

src/Client.cpp
Old names will be available for a while, then removed.
self-message is superseded by echo-message and will be removed in future
too.
Also remove CAP CLEAR, because it's useless, and got deprecated in
IRCv3.1.
=> Update capability names as they are named in IRCv3.2.

modules/data/webadmin/tmpl/settings.tmpl
Adding this class makes it so the input has a defined width.
Fixes znc/znc#446
=> Add third class to the port input [Fixes #446]

configure.ac
Otherwise building ZNC in debug mode gives a flood of warnings:
_FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
=> Fix #887: define _FORTIFY_SOURCE only for optimized release builds

include/znc/Chan.h, modules/controlpanel.cpp, src/Chan.cpp
The trick is to set the value to "-" in controlpanel. Notice that
controlpanel supports wildcards, so this can be used to easily
reset all channels back to defaults if desired.
=> Allow reseting channel specific AutoClearChanBuffer & Buffer settings

modules/log.cpp
Continuation of #695 - hope this is OK, this is a feature I'd really like to see added and the original PR seemed abandoned.
Changed the argument parsing to use `sArgs.Token(uIndex)` to allow any order of arguments.
Maybe the same thing is possible with `for (CString& sArg : vsArgs)` but I couldn't see how to grab the element in the next index. Let me know if this is the preferred way to do it.
Also see inline comments.
=> log: Add -timestamp option (cont.)

CONTRIBUTING.md
Specify unmodified ZNC in case the issue is caused by modified ZNC (such as
the SSL certificate validation check removal or firre webadmin theme
(see znc/znc#384 where after fixing patches have reintroduced it)).
<s>Thanks to @kerio92 & @Zarthus for wording suggestions.</s> DarthGandalf reworded it.
[CI SKIP]
=> CONTRIBUTING.md: ask for unmodified ZNC

src/User.cpp
This can be useful in various situations, for instance for quit messages.
=> Add an %empty% substitution in ExpandString that expands to the empty string.

src/HTTPSock.cpp
Fixes #1077 
It still needs to be tested / confirmed that the webadmin module don't need to access the session cookie by JavaScript.
=> Set HttpOnly for session cookie

znc.service.in
network.target only means that the network management is up, it doesn't
mean that there is connectivity.
network-online.target means that the network management thinks that
there is network connectivity which means that the system has IP
address.
https://wiki.freedesktop.org/www/Software/systemd/NetworkTarget/
=> znc.service.in: start after network-online.target

modules/certauth.cpp, modules/lastseen.cpp, modules/route_replies.cpp
I checked all modules that I had loaded and only these three in addition to perform (https://github.com/znc/znc/pull/1102) and cert (https://github.com/znc/znc/pull/1103) are missing descriptions in commands.
=> Add descriptions for missing commands in lastseen & certauth & route_replies

.travis.yml
When fast_finish is True, Travis will inform that the build has failed
when one build fails which is usually desirable instead of waiting for
everything to finish.
However builds that haven't finished yet will continue, this doesn't
stop them or do anything else to them.
`travis lint` passes so,
[CI SKIP]
=> .travis.yml: enable fast_finish

src/Utils.cpp, src/znc.cpp
ZNC previously sent 'ok' on a new line every time a process went alright in CUtils::PrintStatus
No longer is this the case! 
ZNC now remains silent when everything is going well.
Output:
```
[ .. ] Checking for list of available modules...
[ .. ] Opening config [/home/zarthus/.znc/configs/znc.conf]...
[ .. ] Loading global module [webadmin]...
[ .. ] Binding to port [+1111]...
[ ** ] Loading user [zarthus]
[ ** ] Loading network [freenode]
[ .. ] Adding server [chat.freenode.net +6697 ]...
[ .. ] Loading user module [chansaver]...
[ .. ] Loading user module [controlpanel]...
[ .. ] Forking into the background...
[ >> ] [pid: 14233]
[ ** ] ZNC 1.7.x-git-441-d66cb36 - http://znc.in
```
Previously:
```
[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config …
```
=> Remove 'ok' from bootup

modules/alias.cpp
This fixes issue znc/znc#1114 - and also a small consistency fix
=> alias: add 'dump' command to copy your config between users.

src/IRCNetwork.cpp, src/User.cpp
Allows use of %network% in ExpandString for CIRCNetwork.
Additionally, the alphabeticizing was just a nice touch. I found it difficult to navigate the existing list.
Fixes #1115
=> Expandstring network, alphabeticize expandstring list

src/ClientCommand.cpp
This updates the connect command in *status to retrieve the next server
object before triggering the jump, thereby allowing it to display the
next server's name rather than a generic message.
=> Fix #1147: show new server name when jumping

src/ClientCommand.cpp
Reverts znc/znc#1149
This made it to jump over the next server, skipping one (and actually lying to user about what server it connects to)
=> Revert "Fix #1147: show new server name when jumping"

modules/simple_away.cpp
To support upgrading, %s will still be replaced with the Away Time. but we just refer to it
as %awaytime% to be consistent with ExpandString substitutions.
=> Use ExpandString for simple_away, rename %s to %awaytime% to follow ExpandString standards

.travis.yml
http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/ and
we have been talking forever about moving notifications to #znc-dev and
there have been multiple PRs for that.
-y is apparently needed with trusty or apt hangs forever waiting for
yes/no.
=> .travis.yml: use Ubuntu Trusty & #znc-dev

modules/simple_away.cpp
This adds a new option and command to the module, "MinClients", that
specifies the minimum number of clients that must be connected for the
module to considered the user as available.  If fewer clients are
connected than the minimum, the user will be marked away, even if there
are still clients attached.  The default value is "1", which replicates
the existing behavior of the module.
To modify the MinClients value, `/msg *simple_away MinClients [<value>]`
is available.  Running the command without parameters will display the
current value instead of modifying it.
=> Fix #1133: Add MinClients option to simple_away

modules/log.cpp
@JackHarley noticed this while playing around with the znc-backlog module. (https://github.com/FruitieX/znc-backlog/issues/13), and old PR: #590 
While it is indeed true that IRC is not case sensitive, ZNC still thinks that users and the configured names for networks are. This means that the log path is different depending on which scope the module is loaded in. As a global module both $USER and $NETWORK would be lowercase, but loaded as Network module they would be whatever casing they are in ZNC configs. Issue being difficulty to handle the different scenarios in other modules (znc-backlog) or external scripts.
This will break log folders for people once again.
=> Make $USER and $NETWORK case sensitive in logs

include/znc/znc.h, src/Listener.cpp, src/znc.cpp
This pull request adds backwards compatible support for a new configuration variable, `SSLKeyFile`, allowing separation of SSL keys and cert files. It depends on https://github.com/jimloco/Csocket/pull/58 (please note that CI builds are expected to fail for this reason). Documentation and `--makecert` support should still be added, but I wanted to make this request first for feedback.
Eventually I would like to add support for an initial persistent read of the files into memory, which will allow ZNC to run initially as a root service, read protected keys and immediately drop privileges to the znc user. This will be particularly helpful to support https://letsencrypt.org certificates without a wrapper.
=> support for separate SSLKeyFile configuration

modules/notify_connect.cpp, test/Integration.cpp
If someone connects to ZNC as `username@identifier/network`, the module will now show that *identifier*. When the identifier is not provided, the behavior is unchanged.
> [Notice] -\*status- \*\*\* username@identifier detached (from 127.0.0.1)
=> Show client identification in notify_connect module

modules/route_replies.cpp, modules/sasl.cpp
This alters the `sasl` and `route_replies` module to use the hook `OnRawMessage` or `OnNumericMessage` instead of `OnRaw`, to ensure the module catches any messages from the server that it intends to catch, regardless of tags applied before the actual command/numeric.
`OnRaw` delivers to the plugin raw lines directly from the IRC server, whose tokens can be unpredictable depending on if the server has `server-time` enabled or if the IRC server prefixes `AUTHENTICATE` or the numeric with the server name, etc. - checking if the first parameter of a raw message is "AUTHENTICATE" was unpredictable for our use, as it would only work if the server doesn't prefix the message with either of these tags. (We could only interpret the raw line `AUTHENTICATE +`, not `@time=2015-12-21T18:11:52.000Z …
=> modules/sasl, modules/route_replies: interpret messages even if they have prefix tags (resolves #1212)

src/ZNCString.cpp, test/StringTest.cpp
The IRC message `\x03,03test` represents resetting foreground colour, following by setting a background colour. This currently wasn't correctly stripped in ZNC's StripControls.
I've also added test coverage for the rest of StripControls.
=> Strip background colours when we reset foreground

modules/fail2ban.cpp
It wasn't tested in production, but it does compile.  The changes are abysmal enough (and evidently copy-paste from working modules) that it shouldn't be a concern.
This pull request specifically targets the master branch.
=> fix #1271: Disallow non-admin users to use fail2ban commands

src/Client.cpp
I noticed ZNC just statically calls it "AUTH", but realistically it should send the users nickname. No client really has trouble interpreting this, but it's good to be correct (and consistent, see L84) all the same.
https://tools.ietf.org/html/rfc1459#section-4.4.2
=> Always send the users name in NOTICE when logging in.

src/Client.cpp
We preserve the time of the original message by making a copy of it,
and just changing the nick, which we then pass on to the CMessage
overload of PutClient, which converts the timestamp into a @time tag.
=> Don't strip timestamp when sending echo-messages

include/znc/Utils.h, src/Buffer.cpp, src/Message.cpp, src/Utils.cpp, src/ZNCDebug.cpp, test/UtilsTest.cpp
The gettimeofday function returns 0 for success, not for failure. As a
result of the inverted logic we were losing millisecond precision when
parsing incoming messages on non-HAVE_CLOCK_GETTIME systems (macOS).
A followup commit does a bit of cleanup to prevent this kind of error in the future, by centralising the way we get the current time.
=> Fix inverted gettimeofday() return value handling

include/znc/Modules.h, src/Modules.cpp, src/Query.cpp
Allows hooking into query buffer playback before and after all the
lines of the query buffer are replayed. The EModRet return value
has no effect at the moment, but may be used in the future to e.g.
prevent playback. The Chan version of these signals use EModRet to
skip emitting the status message, but not the whole playback.
=> Add OnPrivBufferStarting/Ending signals, similar to Chan buffers

ChangeLog.md, include/znc/IRCNetwork.h, include/znc/Socket.h, modules/controlpanel.cpp, modules/data/webadmin/tmpl/add_edit_network.tmpl, modules/webadmin.cpp, src/IRCNetwork.cpp, src/Socket.cpp
Added the following two network-specific configuration options that can
be changed via controlpanel or webadmin:
* TrustAllCerts: Will trust ALL certificates when enabled, effectively
disabling TLS certificate validation. This has precedence over TrustPKI.  
Default value: false
* TrustPKI: Whether or not to trust PKI-valid certificates. Setting this
to false will make znc trust only trusted certificates added by the
user.  
Default value: true
With default values, behavior is exactly the same as before.
This is based on the work of Roelf Wichertjes. See YourBNC/znc@5c747598.
See znc/znc#866.
----
This would resolve znc/znc#866.
See [my comment there](https://github.com/znc/znc/issues/866#issuecomment-220449552) for my reasoning why I implemented it this way.
=> Add network-specific settings for cert validation

Makefile.in
GoogleTest has moved to new hosting, simple fix.
=> Fix `make test` in 1.6.x

modules/schat.cpp, src/SSLVerifyHost.cpp, src/Utils.cpp, src/main.cpp
As promised in #1310, this deals with making znc code compile against OpenSSL 1.1 with no errors or relevant deprecation warnings.
I have compiled these changes with OpenSSL versions 1.1.0, 1.0.2h and 0.9.8g on a Debian system - all successfully. I've also run `make test` (after fixing it for the 1.6.x branch, let me know if you're interested) on each version - pass every time, although I'm not sure how much that's really testing. I have not yet used the built znc (other than `znc -v`) or attempted to exercise any of the features these changes affect.
Please make sure I haven't done anything obviously stupid and then I'll happily "eat my own dog food" with OpenSSL 1.1 - hopefully others can test with older OpenSSLs. I'm not a user of the schat module, so also hope someone can test that …
=> OpenSSL 1.1 compatibility

modules/keepnick.cpp, test/integration/main.cpp
keepnick will now abort if it encounters an unrecoverable error rather than flooding the ircd every 30 seconds with a NICK. The user will be notified that keepnick cannot change nicks due to a numeric from the ircd. 
What the user will have to do depends on the error, which the ircd provides a description of. In the case of charybdis an example would be "Cannot change nickname while banned on channel". While it's possible to catch this, part the channel, change nick, and rejoin -- this causes noise, may not work, you may be affected by multiple bans (which becomes more complex and is more error prone), and it may be a collision between numerics.
In short, if this is nothing keepnick can solve, it stops bothering and alerts the user they need to fix it.
In the backend we've also modernized …
=> keepnick: improve behaviour by listening to ircd-side numeric errors

version.sh
I'm not sure when the `format` argument was added to `git log`, but it seems to be an alias for `pretty` (ie both exist in current versions of git). I noticed this was failing on my ancient system that's stuck with git 1.5, this makes it work.
Also, `ignore-submodules` is not understood by ancient `git status` - I believe the expected output would be achieved by simply removing this argument, but it's not important since it fails gracefully enough and fixing it so newer git doesn't fail seems more complicated.
=> Fix version.sh for ancient git

include/znc/Modules.h, include/znc/version.h, make-tarball.sh, src/Modules.cpp, src/znc.cpp
Make version checks more strict.
This finishes attempt to preserve ABI between patch versions. That
didn't work well, and the people who could make it work, left the
project already.
=> Refactor the way how modules are loaded.

modules/sasl.cpp
With #1338, the parameter username was made optional, but the help
was not changed to reflect this.
ref. https://github.com/znc/znc/pull/1338#issuecomment-270563035
=> SASL: More informative help command for Set.

modules/Makefile.in
This alphabetically sorts the modules/ we compile so
that it's easier to see where we're currently at.
Fixes #1358
=> makefile: alphabetically sort the modules we compile

modules/sasl.cpp
Fixes #1291 for the stable branch.
Ref. https://github.com/znc/znc/commit/9864b2716a0274e046867aba83962b979d078bdd for the original fix by psychon with dgw, this is merely a non-cherry-pick backport as I realized too late it was already fixed elsewhere in the same manner.
(feel free to cherry pick their commit instead)
=> [sasl] Do not try to convert entire "verbose" command to bool.

src/main.cpp
Changes the output of `znc --help` to order the arguments in alphabetical order.
=> cli: help: sort arguments alphabetically

.gitignore
=> Add /install_manifest.txt and /install_manifest_*.txt to .gitignore.

modules/crypt.cpp
Don't use a key which is a valid nickname, now changed to "@nick-prefix@" instead.
If you had loaded the crypt module before, the old nick-prefix will still remain in your config but can safely be removed.
Also check if the nick-prefix and status-prefix aren't the same or overlapping, "*" or "." are then used depending on either value. If they would be the same, you would be messaging a module instead of a user.
And if they'd overlap, depending on the nick, you could be messaging a module as well.
=> Fixes for the nick-prefix in the crypt module

test/integration/main.cpp
Right now this contains a WIP comment to test for some CVE again: https://github.com/znc/znc/commit/d0dc463ce3f0328501ced908a073c51dc6c226b4
I will remove this after Travis confirms that the test still catches this error.
=> Some test suite stuff, mostyl speed

modules/crypt.cpp, test/integration/main.cpp
Hides the internal keyword from ListKeys and adds the NickPrefix comand to view and optionally set another prefix.
=> Add NickPrefix command to view and set the nickprefix.

modules/crypt.cpp
Moves code from OnUserMsg, OnUserNotice and OnUserAction to one function.
=> Refactor duplicate code in crypt module.

src/IRCSock.cpp
Calls to `CIRCSock::Quit()` eventually result in the object's destructor being called, which itself calls `CIRCSock::Quit()` again. Avoid sending multiple quit messages to the remote server by checking if the underlying socket is already marked for closing.
Fixes #1392.
=> Don't try to quit multiple times (#1392)

modules/block_motd.cpp
There were some problems with the existing implementation:
- If a server has no MOTD `m_bTemporaryAcceptMotd` would be set to true and then subsequent MOTDs would be sent to the current user or another user who has the same instance of the block_motd loaded.
- If the module is loaded globally then the `m_bTemporaryAcceptMotd` could be changed by other users and this could lead to timing issues where one user asks for an MOTD and another user may get a full or even partial MOTD. This could lead to sending a start motd or end motd separately and potentially breaking clients.
- Lastly, we should send "MOTD" instead of "motd" as the IRC command to a server as per RFC1459.
This is my first PR in ZNC in some years so please review with caution incase I did something wrong or there is a better …
=> Fix block_motd incorrectly tracking state on which user requested MOTD

include/znc/Modules.h
This fixes the misleading documentation for `OnUserQuitMessage()` ~and adds a new module hook (`OnQuitIRCMessage()`) that is called when ZNC quits an IRC network~.
=> Fix OnUserQuitMessage documentation

modules/log.cpp
Since `OnIRCDisconnected()` doesn't include the quit message, and `OnQuit()` isn't called when the user quits, we need to hook `OnSendToIRC()`.
=> Log user quit messages

modules/missingmotd.cpp
Since the nick argument is missing, "MOTD File is missing" is taking the nicks place and could lead to client confusion that the 422 command is sent to "MOTD File is missing".
Found a report of this against a client because the client was updating the nick from the MOTD missing message.
=> missingmotd: Include nick in IRC numeric command

include/znc/Client.h, include/znc/Modules.h, src/Client.cpp, test/ClientTest.cpp
This pull request introduces `CClient::SetTagSupport()`, which modules can use to indicate that a particular tag is supported by a client, and also updates the core to send to clients all tags that they support.
=> Support custom message tags

src/Client.cpp, src/IRCNetwork.cpp
Shows the user when DEBUG mode is enabled.
```
(14:45:47) * Connect retry #1 server.com (+32498)
(14:45:47) Caps supported: batch cap-notify echo-message multi-prefix server-time userhost-in-names znc.in/batch znc.in/self-message znc.in/server-time-iso
(14:45:48) Caps set: multi-prefix server-time userhost-in-names
(14:45:48) Password required
(14:45:47) -irc.znc.in- *** ZNC is presently running in DEBUG mode. Sensitive data during your current session may be exposed to the host.
(14:45:47) -irc.znc.in- *** You need to send your password. Configure your client to send a server password.
(14:45:47) -irc.znc.in- *** To connect now, you can use /quote PASS <username>:<password>, or /quote PASS <username>/<network>:<password> to connect to a specific network.
```
```
(14:45:49) <*status> ZNC …
```
=> transperancy: Make the user aware that DEBUG mode is enabled.

src/HTTPSock.cpp
Cross-site request forgery is a common security issue that affects many web applications. ZNC mitigates the risk of CSRF in the same manner as many other applications - by making use of a token mechanism. A `<input type="hidden" name="_CSRF_Check" value="token">` field is included in all forms and when the browser `POST`s the data, the token is checked. This ensures that a cross-origin `POST` will be unsuccessful because the malicious site will not know the token's value.
The `SameSite` attribute can be applied to cookies. Browser such as Chrome and Opera (which implement the spec) will refuse to send the cookie along with potentially dangerous requests which originate from another domain. `SameSite` can work in two modes of operation:
* Strict: Cookies are not send for a request from a …
=> Use SameSite=strict cookies consistently

modules/crypt.cpp
Update the crypt module when LibreSSL is being used
=> Update crypt module: Fix for LibreSSL

modules/controlpanel.cpp
For a programmer, "double" makes sense as a data type, but for a human this is just a number.
=> controlpanel: Change "double" to "number"

src/IRCSock.cpp
Unless there's a very good, specific reason for it, I think this behaviour should be avoided. I thought of keeping the old behaviour if the channel wasn't valid, but I don't see the point unless there's something I'm not seeing, which might be likely.
Many IRC clients call WHO on every channel to update and format nick lists and such, and this dramatically reduces performance during such requests, to the point where I had over 10s latency to normal channel messages. Some tests I did pointed me to the WHO query where I found this.
From the tests I've done with this patch, WHO works as expected, including calling it on a channel or on a potential nick including wildcards. No signs of the issue I was having before either.
Even if there's a reason for this behaviour, doing it after more …
=> Avoid calling OnWho on every channel in the network WHO was called in.

include/znc/User.h, include/znc/Utils.h, modules/awaystore.cpp, modules/listsockets.cpp, modules/log.cpp, src/Buffer.cpp, src/User.cpp, src/Utils.cpp, test/UtilsTest.cpp
This pull request adds the prerequisites and implementation for allowing ZNC to display timestamps with sub-second precision.
Notable user-visible changes is that the log module's `-timestamp` parameter, and ZNC's `TimestampFormat` option, now understand the additional formatting sequences `%L` and `%N`. These are non-standard extensions to `strftime`. The characters chosen here use the same syntax as Ruby's `strftime` implementation (though other languages extend `strftime` in a similar way).
=> Add sub-second precision for timestamp formatting

ZNCConfig.cmake.in, modules/CMakeLists.txt, src/CMakeLists.txt
This allows external modules to use newer C++ versions than C++11.
=> Export CMake target more cleanly.

modules/data/cert/tmpl/index.tmpl, modules/po/cert.pot, translation_pot.py
They are ignored in CTemplate, because the string doesn't reference it
as {N}
=> Add comments for translator to .tmpl files

src/Client.cpp
When connecting to many ZNC networks at once, one failed login causes numerous query windows from `*status` to pop up. These can be annoying to close on some clients, so it may be more practical to send these messages as notices.
=> src/Client: send failed logins to NOTICE instead of PRIVMSG

src/FileUtils.cpp
bits are being set in file mode rather than open flags. As a result file permissions get strange bits set.
```
build# ls -l /etc/opt/znc/znc.conf
-rwS------   1 znc      znc        1.62K Feb  9 14:47 /etc/opt/znc/znc.conf
build# stat -c %a /etc/opt/znc/znc.conf
4600
```
=> Stop creating files with odd permissions.

src/Client.cpp
This patch prevents PRIVMSGs from clients from being echoed to other clients if their target has the status prefix. This matches the behaviour in 1.6.x.
=> Fix echo-message regression from 1.6.x

modules/route_replies.cpp
Rizon replies with a 403 if the channel does not exist,
and with a 442 if you're not on that channel.
Resolves #1421
=> route_replies: rizon: [MODE] Add 403, 442 expectations

modules/simple_away.cpp
- convert to utc time
- add tz to the away string subst
Currently the away time (on the same day) is completely useless if you don't know what TimeZone the user is from.
Mild backwards incompatibility if you have a custom string that adds the timezone, but not much we can do about that.
Conflict with #1505
=> simple_away: Convert to UTC time

.ci/Jenkinsfile.crowdin
Changing the shell command to a oneliner broke the script std output.
Changes:
```sh
def modifiedLocales = sh 'git status --short | grep -o -E "[^ ]+\\.po$" | sed "s/.po//g" | grep -o -E "[a-z]{2}_[A-Z]{2}$" | sort -u | tr "\\n" " " | sed -E "s/ $//"'
```
To:
```sh
def modifiedLocales = sh (
script: 'git status --short | grep -o -E "[^ ]+\\.po$" | sed "s/.po//g" | grep -o -E "[a-z]{2}_[A-Z]{2}$" | sort -u | tr "\\n" " " | sed -E "s/ $//"',
returnStdout: true
)
```
per https://stackoverflow.com/a/38783622/3100691
I also added "ci: Add modifiedLocales to git-commit message".
Ref:
Update translations in master (null) 
#1568 opened 15 minutes ago by znc-jenkins  
Update translations in 1.7.x (null) 
#1567 opened 15 minutes ago by znc-jenkins
=> ci: return output of shell commands to stdout

src/FileUtils.cpp
The signal mask is inherited by children, so if we don't remove it
the shell module spawns processes which are accidentally resistant
to most signals.
see: man sigprocmask (znc uses pthread_sigmask, but they act the same)
=> Unblock signals when spawning child processes.

src/znc.cpp
Before this commit, when pUser->SetBeingDeleted(true) is executed, pUser is an empty unique_ptr, because release() was already called on it. Therefore, pUser->SetBeingDeleted is unidefined behaviour.
Also, AddUser only takes ownership of the passed user pointer if it succeeds. In case of a failure, it's the caller's responsibility to delete the user.
Fix this by keeping a raw pointer to the user, and handling it accordingly when AddUser fails.
I have no idea whether SetBeingDeleted is necessary there, leaving it just in case.
Maybe it would be better if we could change the semantics of AddUser to always take ownership of the pointer, or even take unique_ptr, as suggested by DarthGandalf on IRC, but I have no idea how to adapt Python bindings in modpython to such change.
=> Fix memory leak and null dereference in CZNC::LoadUsers

configure.ac, src/Utils.cpp
Prior commit was tested with 1.0.2. This one with 1.1.
This is for 1.7.x
=> Fix compilation without deprecated APIs in OpenSSL 1.1

include/znc/Utils.h, src/ClientCommand.cpp, src/Utils.cpp
(fixes #914)
(obsoletes #1654)
**Note**: this obsoletes my earlier PR. Adding `SetStyle()` provides a cleaner API than patching any function that calls `GetLine()`.
Please see the `requested feedback` section below!
There has been an earlier attempt at cleaning up the tables (#922), but that was reverted later on due to its massive increase in vertical size. My patch is **opt-in**: meaning, only tables that are deemed safe are(quickly and easily) switched to the ChanServ style. I've ported the `/znc help` output as an example.
**old format**: as you can see, the table is completely garbled on narrow screens (let alone mobile)
[znc-status-oldformat](https://user-images.githubusercontent.com/11820748/56472185-e131b700-644a-11e9-8f18-858750f3827e.png)
**new format**: this new format is much …
=> ListStyle (compact) replacement for two-column tables

modules/route_replies.cpp
This has shown up in combination with the recent InspIRCd v3.0.0 release which returns 403 (`ERR_NOSUCHCHANNEL`) to a `NAMES` against an unknown channel - thus causing `*route_replies` to give a response timeout error.
As per [RFC](https://tools.ietf.org/html/rfc1459#section-6.1):
```
401     ERR_NOSUCHNICK
"<nickname> :No such nick/channel"
- Used to indicate the nickname parameter supplied to a
command is currently unused.
```
```
403     ERR_NOSUCHCHANNEL
"<channel name> :No such channel"
- Used to indicate the given channel name is invalid.
```
=> Support both ERR_NOSUCHNICK and ERR_NOSUCHCHANNEL for *route_replies NAMES

modules/autocycle.cpp, modules/certauth.cpp, modules/controlpanel.cpp, modules/crypt.cpp, modules/fail2ban.cpp, modules/lastseen.cpp, modules/log.cpp, modules/notes.cpp, modules/sasl.cpp, modules/watch.cpp, src/ClientCommand.cpp, src/Modules.cpp
this is a follow-up to #1657. it applies the freshly merged CTable::ListStyle to all two-column tables; most importantly all the module help and control panel help, but also any list-something commands with compatible output. excluded are the Q and partyline modules, as they are deprecated. 
below is a list of all the tables with three or more columns; they have not been modified. further discussion will be necessary for them to be adapted.
<details>
<summary>big list of not-modified tables</summary>
```
src/Modules.cpp
ListTimers() // Name | Secs | Cycles | Description
ListSockets() // Name | State | LocalPort | SSL | RemoteIP | RemotePort
src/ClientCommand.cpp
UserCommand() //many
UserPortCommand() //many
modules/dcc.cpp
ListTransfersCommand() // Type | State | Speed | Nick | IP | File …
```
=> listify two-column tables

include/znc/Chan.h, include/znc/Message.h, src/Chan.cpp, src/Client.cpp, src/IRCSock.cpp, src/Message.cpp, test/IRCSockTest.cpp, test/MessageTest.cpp
Some servers may send a colon even if the last parameter doesn't need
it, currently this leads to issues with permission/mode tracking, as the
core doesn't handle the colon properly.
This fix replaces reconstructing the parameter string with just passing a vector of the relevant parameters to CChan::SetModes() and adds overrides for CChan::SetModes() and CChan::ModeChange() that accept the vector instead.
Fixes #1637
=> Rework MODE/RPL_CHANMODEIS handling for trailing args

modules/data/webadmin/tmpl/add_edit_network.tmpl
Per IRC, this wording is confusing and doesn't clearly denote the consequences, a less knowledgeable user may disable this not knowing what a PKI is
=> TrustPKI: Better wording in webadmin

modules/sasl.cpp
The specification requires AUTHENTICATE information to be split into
chunks of size 400. This commit implements the necessary chunking.
Fixes: https://github.com/znc/znc/issues/942
Signed-off-by: Uli Schlachter <psychon@znc.in>
---
All testing that I did is the following. I briefly looked into automating a test for this, but instead decided for this approach. Feel free to also include these tests somehow.
```diff
diff --git a/src/main.cpp b/src/main.cpp
index d63fed6d..c6bfd2cf 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -291,7 +291,53 @@ static void seedPRNG() {
srand(seed);
}
+static VCString partition(const CString &sAuthLine) {
+    VCString result;
+
+    /* The spec requires authentication data to be sent in chunks */
+    const size_t chunkSize = 400;
+    for (size_t offset = …
```
=> sasl: Fix sending of long authentication information

modules/controlpanel.cpp
Added NoTrafficTimeout User variable to the list of User variables in the controlpanel module. Resolves #1693.
=> Add NoTrafficTimeout User variable to controlpanel.

webskins/_default_/pub/_default_.css
Fix broken css after text edit (https://github.com/znc/znc/pull/1670)
Screenshot: https://imgur.com/a/xbtIAHS
The deleted css lines are not needed.
1. Every element has a min-width of 0
2. Every element has margin: 0 (inherited from * on line 3), so subsection doesn't need the margin property.
=> Web: fix broken layout after text edit

webskins/_default_/pub/_default_.css
Css was not completely right for all browsers after #1711.
1. A little less width for the checkbox labels works for all browsers
2. max-width instead of width (conflict with "Global Settings" -> first table)
3. More spacing between "Trust the PKI" and subsequent headline "Servers of this IRC network:" - https://imgur.com/a/8zlBYNI
4. Proper way to "clear: both" for subsection (:after pseudo element)
=> Web: fix small css errors after #1711

src/ZNCString.cpp
This PR fixes wrong size argument passed to `strncasecmp` function when it was invoked to check if the string contains HTML entities.
=> Fix incorrect html entities parsing in ZNCString.cpp

modules/data/webadmin/tmpl/add_edit_network.tmpl, modules/data/webadmin/tmpl/add_edit_user.tmpl, modules/data/webadmin/tmpl/settings.tmpl, webskins/_default_/pub/_default_.css, webskins/_default_/tmpl/BaseHeader.tmpl, webskins/_default_/tmpl/DocType.tmpl
according to w3c,
* `<?xml` syntax is deprecated in html: XML processing instructions are not supported in HTML
* The `align` attribute on the `td` element is obsolete and layout be done in css
* [polyglot html](https://www.w3.org/TR/html-polyglot/) is being deprecated
=> Web: remove legacy xhtml syntax

src/znc.cpp
Reworded the warning just a little bit to accommodate both ports. Let me know if you want the specific messages back, and I would happily do that with some string templating magic.
=> Extend port warning to 6697

modules/sasl.cpp
ZNC's sasl module would forward any received 908 (RPL_SASLMECHS) numeric to its own clients which do not have the SASL capability enabled.
=> Don't forward 908 numeric to client

CMakeLists.txt, NOTICE, include/znc/Message.h, src/CMakeLists.txt, src/Message.cpp, test/MessageTest.cpp, third_party/bpstd/bpstd/string_view.hpp
It's a bit too early yet to require C++17 so the implementation from
~~abseil-cpp~~BackportCpp is used instead.
Fixes https://crbug.com/oss-fuzz/34413 - slow message parsing on huge
messages. In real word, messages can't be that big, because CSocket
enforces a line length limit.
This can be considered a regression of 1.7.0, because before it, instead
of gathering params into a vector, code was searching 1st word in the
string, then 2nd word, then 3rd word, starting from beginning each time.
It was not very efficient, but the number of passes over the string was
limited.
=> Rewrite message parsing using string_view

src/main.cpp
Right now, running with `-f` or `--foreground` prints:
```
Staying open for debugging [pid: 251]
```
Which is kinda confusing and I was worried if some debug functionality was exposed.
This PR will print the above message only if `-D` or `--debug` is given.
=> fix foreground message to not imply that debug mode is on

modules/route_replies.cpp
This is very similar to the behaviour for route_replies with MODE, in which MODE requests (not change) are routed. Here I am routing any TOPIC request excluding TOPIC change only back to the client that requested it.
=> Route TOPIC requests to client in route_replies

modules/crypt.cpp
https://github.com/libressl-portable/openbsd/commit/848e2a019c796b685fc8c5848283b86e48fbe0bf
https://github.com/libressl-portable/openbsd/commit/3789e379353c1d53313a249461b3d735de4ac742
The build only fails now with LibreSSL 3.5 because the structs inside these functions have become opaque.
=> DH_set0_pqg and DH_get0_key have existed since LibreSSL 2.7

src/IRCNetwork.cpp, src/User.cpp
Building with CFLAGS="-flto -Werror=odr -Werror=lto-type-mismatch
-Werror=strict-aliasing" CXXFLAGS="-flto -Werror=odr
-Werror=lto-type-mismatch -Werror=strict-aliasing" LDFLAGS=-flto fails
due to a violation of the one definition rule. There are two different
definitions of TOption that are both linked into the znc binary.
Fix this by putting them into anonymous namespaces.
Fixes: https://github.com/znc/znc/issues/1834
Signed-off-by: Uli Schlachter <psychon@znc.in>
=> Fix an ODR violation

modules/clientnotify.cpp, test/integration/framework/znctest.cpp, test/integration/framework/znctest.h, test/integration/tests/modules.cpp
This PR adds:
- an integration test for [`clientnotify module`](https://github.com/znc/znc/blob/master/modules/clientnotify.cpp)
- a new option `NewNotifyOn` to the module which determines whether notifications should be sent when a client with a new IP, new identifier or for both cases should be sent
- the options to use identifiers in the integration tests
Questions for the reviewer:
- Should the Code be formatted given the `.clang-format` config? If yes I will push the reformatted code in another commit
- What do you think about the naming of the new option?
- Should the one [text] option be split into two boolean ones or stay as is?
Fixes #1840
=> `clientnotify.cpp`: add new option and test existing code

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where ZNC already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and also moves the fuzzing closer into the development workflow. CIFuzz has a variety of features which can be found in the URL above. In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
=> CI: add CIFuzz GitHub action

src/Utils.cpp, test/UtilsTest.cpp
I'm not at all certain if this fix will meet your standards, but it does resolve #1773. It's based on other timezone manipulation code in `Utils.cpp`.
Please let me know if changes are needed.
=> Fix ParseServerTime to use UTC

modules/log.cpp
This commit adds the account name for identified users to "Joins" lines in logs generated by the log module.  It can get the account name from either the account tag (if the account-tag capability is requested) or the extended-join info (if the extended-join capability is requested).  The current version of ZNC requests both, but this feature will still work if the IRC server only supports one or the other.
=> Add account to joins for the log module.

src/Client.cpp, test/IRCSockTest.cpp, test/integration/tests/core.cpp, test/integration/tests/modules.cpp, test/integration/tests/scripting.cpp
Some clients will reuse query windows as the client thinks its just a nick change if you have a existing query window with a module and a different one messages you.
Fix that by using the modules name as the ident.
Current format:
```
*status!znc@znc.in
*sasl!znc@znc.in
```
New format:
```
*status!status@znc.in
*sasl!sasl@znc.in
```
Client reusing query windows:
```
18:18:49 -!- Irssi: Starting query in Libera.Chat with *controlpanel
18:18:49 <KindOne> addnetwork
18:18:49 <*controlpanel> Usage: AddNetwork [user] network
18:21:47 -!- *controlpanel is now known as *status
18:21:47 <*status> IRC connection timed out.  Reconnecting...
18:22:06 <KindOne> disconnect
18:22:06 <*status> Disconnected from IRC. Use 'connect' to reconnect.
```
=> Use module names as the module ident.

modules/route_replies.cpp
solanum uses 337 to report when a user's idle time is hidden by umode +I
=> route_replies: add 337 to whois

Dockerfile
In https://github.com/znc/znc-docker/pull/28 the location of the init scripts was moved which broke the logic to copy all the init files once the docker submodule was updated in 5d7aa0f7d44cb0d686881ced5b409c3d0569e7ca. Consequently only `30-build-modules.sh` was available in the build docker image. 
We fix this issue by also including all startup-sequence subfolders.
=> docker: Fix startup-sequence locations

modules/modperl/modperl.i
Use of newAV_alloc_x() was added in a7dffb8f (Add modperl support for sasl, 2025-03-16), but it has the unintended consequence of increasing the minimum Perl version a bit more than desired.  Replace it with the roughly equivalent code as documented in perlapi(1), which can be read online at <https://perldoc.perl.org/perlapi#newAV>.
Fix #1966
=> modperl: avoid newAV_alloc_x which requires perl >= 5.35.1
