znc/znc

include/znc/znc.h
modules/data/webadmin/tmpl/settings.tmpl
modules/webadmin.cpp
src/znc.cpp

Add a global setting whether to show ZNC version or not

---

modules/sasl.cpp

This is the same as #793, but for correct branch.
Closes #793

modules/sasl.cpp: update help for "set"

---

modules/autoattach.cpp
modules/autocycle.cpp
modules/autoop.cpp
modules/autovoice.cpp
modules/log.cpp
modules/watch.cpp

Mods: use case-insensitive wildcmp() for channel/host matching

---

README.md

[ci skip]
closes #747
closes #834
closes #274

Readme dependencies

---

src/Chan.cpp

Write config file when channel is removed (#932)

---

include/znc/Utils.h
src/Utils.cpp

Fix #743
Fix #914
Close #922 
```
[08 апр, 23:38:22] <*status> ------
[08 апр, 23:38:22] <*status> Command: ListNicks
[08 апр, 23:38:22] <*status> Arguments: <#chan>
[08 апр, 23:38:22] <*status> Description: List all nicks on a channel
[08 апр, 23:38:22] <*status> ------
[08 апр, 23:38:22] <*status> Command: ListServers
[08 апр, 23:38:22] <*status> Description: List all servers of current IRC network
[08 апр, 23:38:22] <*status> ------
[08 апр, 23:38:22] <*status> Command: AddNetwork
[08 апр, 23:38:22] <*status> Arguments: <name>
[08 апр, 23:38:22] <*status> Description: Add a network to your user
[08 апр, 23:38:22] <*status> ------
```

Make tables... not so tabular.

---

include/znc/Client.h
src/Client.cpp
src/Query.cpp

http://ircv3.net/specs/extensions/echo-message-3.2.html
TODO: Add echo-message support to CIRCSock when IRCds start supporting it.
Manual echoing won't be necessary for networks that support echo-message.

Implement IRCv3.2 echo-message capability on the "client side"

---

modules/data/webadmin/tmpl/settings.tmpl

Makes the styling extend to the whole table header
Fixes the first part of znc/znc#446

Add extra td [Fixes #446]

---

modules/data/webadmin/files/webadmin.css
modules/data/webadmin/files/webadmin.js
modules/data/webadmin/tmpl/add_edit_user.tmpl
modules/data/webadmin/tmpl/listusers.tmpl

Here's what it looks like
I still need to sort out the fixing odd and even rows after the tables are sorted.
Mainly I wanted your opinion on
* Whether this vanilla js solution is fine, or should I use the recent-ish added jquery for maximum compatibility. I believe the main limitation here is its >=IE9 with some of the functions I use. 
* Are the simple little arrows okay
* Is the formatting etc fine
Personally I agree with psychon on the issue page that using a really hefty library is kinda overkill. Which is why I opted to just make a simple sorting function.

Implement table sorting in webadmin, addresses #40

---

modules/data/webadmin/files/webadmin.js
modules/data/webadmin/tmpl/add_edit_network.tmpl
webskins/_default_/pub/_default_.css

Make server editor in webadmin more fancy, when JS is enabled

---

include/znc/IRCNetwork.h

IRCNetwork.h: lower ping frequency & timeout

---

README.md

README: fix formatting & links

---

include/znc/Client.h
include/znc/IRCSock.h
src/IRCSock.cpp

Add support for account-notify and extended-join

---

include/znc/Utils.h
modules/fail2ban.cpp

This PR implements everything else from #534 except the ban notices part.

fail2ban: configurability & commands

---

src/IRCSock.cpp

src/IRCSock.cpp: use *status as kicker

---

src/Client.cpp

Thanks to jaybe for complaining about this.

Support "CAP :END"

---

modules/adminlog.cpp
modules/ctcpflood.cpp
modules/flooddetach.cpp
modules/lastseen.cpp
modules/log.cpp
modules/simple_away.cpp
src/Buffer.cpp
src/FileUtils.cpp
src/IRCSock.cpp
src/User.cpp
src/WebModules.cpp
src/ZNCDebug.cpp
src/main.cpp
src/znc.cpp

Signed-off-by: Gustavo Zacarias <gustavo@zacarias.com.ar>

Add <time.h> includes where appropiate

---

include/znc/znc.h
src/znc.cpp

- SSLCiphers
- SSLProtocols
- SSLCertFile

CZNC: add missing SSL-related getters and setters

---

CONTRIBUTING.md

add simple CONTRIBUTING.md

---

src/Message.cpp
test/MessageTest.cpp

Even though eyeless Russian smileys are neat, like, much cooler than those childish winky winky blinky ;) ones et cetera, it seems unfair to cut out eyes from everyone's smileys.

Bring back the eyes

---

modules/modpython/pyeval.py

This PR adds the pyeval module I wrote many years ago.
/cc @DarthGandalf
http://wiki.znc.in/Pyeval

Add the pyeval module

---

.travis.yml

Travis: try to simplify matrix config

---

modules/controlpanel.cpp

Fix command syntax of GetNetwork and SetNetwork.

ControlPanel: Move syntax of GetNetwork and SetNetwork

---

modules/stickychan.cpp
src/Client.cpp

- OnUserJoinMessage()
- OnUserPartMessage()
- OnUserTopicMessage()
- OnUserActionMessage()
- OnUserCTCPMessage()
Supersedes #503

Don't require network for OnUserXxxMessage() hooks

---

modules/crypt.cpp

Improves compatibility with mircryption.
Notes:
1. I know the use of `OnRaw` is not suggested, but I cannot find a more appropriate way to intercept the incoming topic message.
2. There's some duplication here, but when I added functions for the individual pieces of functionality needed to handle outgoing messages, it did not seem to significantly improve readability.
I'm open to all comments and suggestions.

Expand crypt module to cover Notices, Actions & Topics

---

modules/perform.cpp

Thanks @ChasedSpade
Closes #1100
Closes #1102

perform: add descriptions for commands

---

modules/clientnotify.cpp

Fixes a weird sentence in clientnotify syntax help.

Fixes a weird sentence in clientnotify syntax help.

---

modules/block_motd.cpp

blockmotd: Allow overriding via command

---

.travis.yml

.travis.yml: encrypt IRC notification settings

---

znc.service.in

znc.service.in: add datadir & instructions

---

Makefile.in
configure.ac

Mentioned in #1165 and found by @BlaXpirit.

Fix bindir in service file

---

include/znc/znc.h
src/Chan.cpp
src/znc.cpp

This prevents chansaver from causing configuration file writes so frequently.

Add config write delay configuration setting

---

modules/sasl.cpp

Fixes #1291. Someone had to make a PR, and I was bored, so…here we are.

[sasl] Do not try to convert entire "verbose" command to bool

---

src/Client.cpp
src/ClientCommand.cpp

This was added in commit 85b84078f8d6c34f6ba13d11f512c824ec459f7a from pull request #1072.
Pull request #1014 would of made this command possible, but it was never pulled.

Remove reference for attaching queries.

---

modules/route_replies.cpp

psychon gets credit for this code change.

route_replies: fix module to check if we are not connected to a network.

---

modules/CMakeLists.txt

Fix OpenSSL CMake build on OS X

---

modules/data/certauth/tmpl/index.tmpl
modules/data/lastseen/tmpl/index.tmpl
modules/data/listsockets/tmpl/index.tmpl
modules/data/notes/tmpl/index.tmpl
modules/data/sasl/tmpl/index.tmpl
modules/data/stickychan/tmpl/index.tmpl
modules/data/webadmin/files/webadmin.js
webskins/dark-clouds/pub/dark-clouds.css
webskins/forest/pub/forest.css
webskins/ice/pub/ice.css

Takes #1308 to the next level by finding all `<td>`'s in `<thead>` and changing them to `<th>`

Use <th> in <thead> instead of <td>

---

modules/nickserv.cpp

This patch will enable the NickServ module to handle messages from the X3 services daemon

nickserv: support messages from X3 services

---

include/znc/Message.h

and exactly a message is.
It annoyed me there was no real way of knowing what each index meant, I spent a few minutes printing everything out with DEBUG() and this should be pretty accurate.

Message.h: Add a comment briefly explaining how to use the class

---

include/znc/Message.h
modules/keepnick.cpp
test/integration/main.cpp

Fix the documentation.
See #1324 and #1325 
@Zarthus

Fix newest additions to keepnick module and write the test for it.

---

include/znc/HTTPSock.h
include/znc/Modules.h
include/znc/WebModules.h
modules/data/samplewebapi/tmpl/index.tmpl
modules/samplewebapi.cpp
src/HTTPSock.cpp
src/Modules.cpp
src/WebModules.cpp
test/integration/main.cpp

This is essentially a duplicate of tzvetkoff's work in #1296 with fixes per the comments on that PR.

Module CSRF override support (mark II)

---

include/znc/User.h
include/znc/Utils.h
src/HTTPSock.cpp
src/User.cpp
src/Utils.cpp
test/CMakeLists.txt
test/UserTest.cpp

Add CIDR support to TrustedProxy setting

---

modules/blockuser.cpp

I noticed a lot of the modules don't have comments/it's hard to figure out what is going on so I thought it would be a good idea to add some comments to help other people trying to develop modules understand what is going on.

Adding some comments to block module

---

.codecov.yml
.travis.yml

Add coverage to Appveyor and Jenkins.
Codecov supports merging results from multiple builds.

WIP Remove dedicated coverage build from Travis.

---

.travis.yml

https://github.com/google/sanitizers/issues/856

Travis: Workaround for broken ASAN

---

modules/controlpanel.cpp

Fixes the remaining part of #1465.
----
Thanks for the hint with GitHub's web editor. I'll better not look at the author of this commit since I bet GitHub came up with a weird mail address for me.

Add missing space in "hasno"

---

.codecov.yml

Improve codecov config

---

src/po/znc.ru_RU.po

From https://crowdin.com/project/znc-bouncer

Update translations in 1.7.x

---

modules/po/autocycle.de_DE.po
modules/po/bouncedcc.de_DE.po
modules/po/controlpanel.de_DE.po
modules/po/q.es_ES.po
modules/po/raw.es_ES.po
modules/po/route_replies.es_ES.po
src/po/znc.de_DE.po

From https://crowdin.com/project/znc-bouncer

Update translations in master

---

translations/id-ID

added Bahasa Indonesia

---

.ci/Jenkinsfile.crowdin

ci: Modify crowdin CI to make better PR descriptions

---

.ci/Jenkinsfile.crowdin

ci: fix broken shell syntax

---

.ci/Jenkinsfile.crowdin

ci: Normalize variable names and string interpolation

---

translations/fr-FR

Add French translation option.

Create fr-FR translation

---

include/znc/User.h
modules/adminlog.cpp
modules/awaystore.cpp
modules/blockuser.cpp
modules/certauth.cpp
modules/controlpanel.cpp
modules/identfile.cpp
modules/lastseen.cpp
modules/log.cpp
modules/modpython/codegen.pl
modules/modpython/modpython.i
modules/modtcl.cpp
modules/notify_connect.cpp
modules/partyline.cpp
modules/savebuff.cpp
modules/send_raw.cpp
modules/webadmin.cpp
src/Client.cpp
src/ClientCommand.cpp
src/IRCNetwork.cpp
src/IRCSock.cpp
src/Modules.cpp
src/Socket.cpp
src/User.cpp
src/WebModules.cpp
src/znc.cpp
test/integration/tests/scripting.cpp

Normalize variable "sUserName" to "sUsername"

---

src/IRCSock.cpp

Fixes #1624
Tested and confirmed non-regressing, though maybe @AndrioCelos's usecase is different from what I tried.

ctcp: Distinguish Channel CTCP Requests and Replies

---

test/integration/tests/modules.cpp

WIP to try and fix the CI for `crypt` module that seems to be broken by [this change](https://github.com/znc/znc/commit/fe8d447a6062c661541361b5587c6172f19bc9ed#diff-98ecca6bbf88f801b67f88a819541c6b)

CI, fix crypt module test

---

include/znc/IRCSock.h
include/znc/Socket.h
src/IRCSock.cpp
src/Socket.cpp

This shouldn't change any behavior.

Backport SSL changes from asio branch (#1639).

---

include/znc/Config.h
include/znc/IRCNetwork.h
modules/data/webadmin/files/webadmin.js
modules/data/webadmin/tmpl/add_edit_network.tmpl
modules/webadmin.cpp
src/ClientCommand.cpp
src/Config.cpp
src/IRCNetwork.cpp
test/ConfigTest.cpp
test/integration/tests/core.cpp
webskins/_default_/pub/_default_.css

Allow ordering of channels

---

modules/modpython/znc.py
src/Translation.cpp
test/integration/framework/znctest.cpp
test/integration/framework/znctest.h
test/integration/tests/scripting.cpp

Rename cmd/desc to command/description

---

CMakeLists.txt
modules/modperl/CMakeLists.txt
modules/modpython/CMakeLists.txt

https://bugs.gentoo.org/878587

Add support SWIG 4.1.0, drop support for < 4.0.2

---

CMakeLists.txt

Useful info:
https://cmake.org/cmake/help/latest/module/CMakePushCheckState.html

CMake: use cmake_{push,pop}_check_state()

---

CMakeLists.txt
include/znc/Utils.h
include/znc/zncconfig.h.cmake.in
src/Utils.cpp
src/znc.cpp

See individual commit messages for description.

Fix undef hostname

---

include/znc/Listener.h
include/znc/znc.h
modules/webadmin.cpp
src/ClientCommand.cpp
src/Listener.cpp
src/znc.cpp
test/integration/main.cpp

This implements https://github.com/znc/znc/issues/1240. So far, I did not do much testing of this (feel free to test this!). Also, a little more work is needed so that listing listeners and adding/removing listeners supports this feature properly. However, I'm out of time for this and lazy.
So: Feel free to pick this up and continue working on it.

WIP: Add support for listening on an UNIX socket

---

modules/sample.cpp

sample: Use newer On...Message events.

---

modules/stripcontrols.cpp
test/integration/tests/modules.cpp

Added OnTopicMessage and stripping for /list and /topic output.
Fixes #1179

stripcontrols: Use new On...Message events.
